spring.application.name=notification-service

server.port=8082



# PostgreSQL — base dédiée notification-service

spring.datasource.url=jdbc:postgresql://localhost:5432/uib_notification

spring.datasource.username=uib_user

spring.datasource.password=uib_password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false



# RabbitMQ

spring.rabbitmq.host=localhost

spring.rabbitmq.port=5673

spring.rabbitmq.username=bnpl

spring.rabbitmq.password=bnpl123



app.rabbit.notification.exchange=notification.exchange

app.rabbit.notification.queue=notification.email.send

app.rabbit.notification.routing-key=notification.email.request

internal.api.key=dev-internal-key-change-in-prod



app.front.base-url=http://localhost:4200



# Email — si false : le consumer RabbitMQ traite quand meme les messages (file videe) mais AUCUN SMTP ne part.

app.mail.enabled=true

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=hamzamaatougui06@gmail.com

spring.mail.password=zryd ilrb csyt fetm

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true



management.endpoints.web.exposure.include=health,info

logging.level.root=INFO

logging.level.tn.uib.bnpl.notification_service=INFO

